[package]
name = "minijq-type-reconstruction"
version = "0.1.0"
edition = "2024"

[lib]
name = "typereconstruction"

[dependencies]
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
